# Generated by Django 6.0.3 on 2026-05-03 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20260503_1529'),
    ]

    operations = [
    ]
