# Generated by Django 6.0.3 on 2026-03-30 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_books_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
            ],
            options={
                'db_table': 'authors',
                'ordering': ['-birth_date'],
            },
        ),
        migrations.RemoveField(
            model_name='books',
            name='author',
        ),
        migrations.AddField(
            model_name='books',
            name='authors',
            field=models.ManyToManyField(related_name='books', to='books.author'),
        ),
    ]
