# Generated by Django 6.0.3 on 2026-03-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_author_remove_books_author_books_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
