# Generated by Django 6.0.3 on 2026-04-06 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('founded_year', models.IntegerField()),
                ('created_ad', models.DateTimeField()),
                ('updated_ad', models.DateTimeField()),
            ],
        ),
    ]
