# Generated by Django 6.0.3 on 2026-04-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='created_ad',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='updated_ad',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
